name: Renovate
on:
  schedule:
    - cron: '0 * * * *'  # Hourly
  push:
    branches:
      - master
    paths:
      - 'source/versions.yml'
      - 'source/compile.sh'
      - 'renovate.json'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }} 