name: Build and Release

on:
  workflow_dispatch:
  
jobs:
  pre-check:
    runs-on: self-hosted
    steps:
      - name: Environment Check
        run: |
          set -x  # Enable command echo
          echo "PATH=$PATH"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "RUNNER_TEMP=$RUNNER_TEMP"
          
      - name: Directory Setup
        run: |
          set -x
          mkdir -p $RUNNER_TEMP || sudo mkdir -p $RUNNER_TEMP
          sudo chmod 777 $RUNNER_TEMP
          ls -la $RUNNER_TEMP
          
  build:
    needs: pre-check
    runs-on: self-hosted
    steps:
      - name: Checkout with Debug
        run: |
          set -x
          [ -d "$GITHUB_WORKSPACE" ] || sudo mkdir -p "$GITHUB_WORKSPACE"
          sudo chmod 777 "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"
          git init
          git remote add origin "https://github.com/$GITHUB_REPOSITORY.git"
          git fetch --depth=1 origin $GITHUB_SHA
          git checkout $GITHUB_SHA
          
      - name: Build with Debug
        run: |
          set -x
          cd "$GITHUB_WORKSPACE"
          bash -x ./source/compile.sh || {
            echo "Build failed with exit code $?"
            ls -la
            exit 1
          }