name: Build ROCm Driver Package

on:
  workflow_dispatch:
  push:
    paths:
      - 'source/**'
      - '.github/workflows/build.yml'
      - 'source/versions.yml'
      - 'tests/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Download Tests
        run: |
          chmod +x tests/download_test.sh
          ./tests/download_test.sh

  build:
    needs: test
    runs-on: self-hosted
    env:
      ROCM_VERSION: "6.0.2"
      BUILD_DIR: "/tmp/rocm-build"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Setup Build Directory
        run: |
          set -x
          sudo rm -rf $BUILD_DIR || true
          sudo mkdir -p $BUILD_DIR
          sudo chown -R $USER:$USER $BUILD_DIR
      
      - name: Download ROCm Drivers
        run: |
          set -x
          cd $BUILD_DIR
          AMDGPU_DEB="amdgpu-install_${ROCM_VERSION}.60401-1_all.deb"
          wget -q "https://repo.radeon.com/amdgpu/latest/ubuntu/pool/main/a/amdgpu-install/${AMDGPU_DEB}"
          dpkg-deb -x "${AMDGPU_DEB}" ./extract

      - name: Create Unraid Package
        run: |
          set -x
          cd $GITHUB_WORKSPACE
          chmod +x source/compile.sh
          ./source/compile.sh

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: rocm-driver-package
          path: |
            ${{ env.BUILD_DIR }}/rocm-driver-*.txz
            ${{ env.BUILD_DIR }}/rocm-driver-*.md5