name: Renovate
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'source/versions.yml'

jobs:
  renovate:
    runs-on: self-hosted
    env:
      RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Renovate
        run: |
          npm install -g renovate
          renovate --platform github \
            --token ${RENOVATE_TOKEN} \
            --autodiscover false \
            --onboarding false \
            --require-config true \
            --repository ${{ github.repository }}