name: Renovate
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master
    paths:
      - 'source/versions.yml'
      - 'source/compile.sh'
      - 'renovate.json'

jobs:
  renovate:
    runs-on: self-hosted
    env:
      RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LOG_LEVEL: debug
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        run: |
          command -v node >/dev/null 2>&1 || {
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
          }

      - name: Install Renovate
        run: |
          npm install -g renovate

      - name: Run Renovate
        run: |
          renovate --platform github \
            --token ${RENOVATE_TOKEN} \
            --autodiscover false \
            --onboarding false \
            --require-config true \
            --repository ${{ github.repository }}