name: Runner Configuration Check

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: self-hosted
    steps:
      - name: Check Runner Process
        run: |
          echo "=== Process Check ==="
          ps aux | grep actions-runner || echo "No runner process found"
          echo "Runner Directory Contents:"
          ls -la ~/actions-runner/ || echo "Runner directory not found"
          
      - name: Check Permissions
        run: |
          echo "=== Permission Check ==="
          echo "Current User: $(whoami)"
          echo "User Groups: $(groups)"
          echo "Runner Directory Permissions:"
          ls -la ~/actions-runner/
          echo "Working Directory Permissions:"
          ls -la .
          
      - name: Check Logs
        run: |
          echo "=== Recent Runner Logs ==="
          tail -n 50 ~/actions-runner/_diag/*.log || echo "No log files found"
          
      - name: Check GitHub Connection
        run: |
          echo "=== GitHub Connectivity ==="
          curl -v https://api.github.com/repos/${{ github.repository }} 2>&1 | grep "HTTP/"
          
      - name: Check System Load
        run: |
          echo "=== System Resources ==="
          uptime
          free -h
          df -h /
          echo "Process Count: $(ps aux | wc -l)"