name: Test Runner Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Basic Check
        run: |
          set -x
          echo "Current directory: $(pwd)"
          echo "Contents: $(ls -la)"
          echo "User: $(whoami)"
          echo "Runner location: $RUNNER_WORKSPACE"